spring:
  datasource:
    #remote
#    url: jdbc:mysql://182.92.88.94:3306/xcx-user-center
#    hikari:
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver #mysql connect >6
    #local
      url: jdbc:mysql://127.0.0.1:3306/xcx-user-center?serverTimezone=UTC
      hikari:
        username: root
        password: zjy123
        driver-class-name: com.mysql.cj.jdbc.Driver #mysql connect >6
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: v1
  application:
    name: user-center
server:
  port: 8070
#rocketmq:
#  name-server: 127.0.0.1:9876

jwt:
  secret: zjy1234567890
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug
